## 🧮 What is NumPy?
###### NumPy (Numerical Python) is a library used for:
###### Creating arrays (instead of Python lists)
###### Doing fast mathematical operations
###### Handling matrices and multi-dimensional data


In [22]:
import numpy as np
# 1D Array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1[4])
print(arr1[1:3])

[1 2 3 4 5]
5
[2 3]


In [ ]:
# 2D Array
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
print(a[0][2])
c=a+b
print(c)
print(a*b)

[[1 2 3]
 [4 5 6]]
3
[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]


In [ ]:
# Special Arrays
print(np.zeros((2, 3)))  # 2x3 matrix of 0s
print(np.ones((3, 2)))   # 3x2 matrix of 1s
print(np.eye(3))         # 3x3 identity matrix

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Useful Shortcuts
print(np.linspace(0,100,3))  
print(np.arange(0,100,3)) 
print(np.random.rand(2, 2))        # Random floats [0.0, 1.0)
print(np.random.randint(1, 10))    # Random integer [1, 9]
print(np.random.randint(1, 10, 5))     

[  0.  50. 100.]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[[0.61495009 0.50323238]
 [0.2191037  0.52822125]]
3
[5 6 7 4 9]


In [7]:
print(np.linspace(0,10))  # if we don't mention no. of values then by default it takes 50 

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [ ]:
# Converting array to list
a=np.array([1,2,3,4,5])
x=a.tolist()
print(x)
print(type(x))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
#Stats
a=np.array([1,2,3,4,5])
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.sum(a))
print(np.std(a))
print(a+1)
print(a ** 2)  
print(a>3)   # give a boolean matrix
print(a[a>3]) # give those values

5
1
3.0
15
1.4142135623730951
[2 3 4 5 6]
[ 1  4  9 16 25]
[False False False  True  True]
[4 5]


In [ ]:
A=np.array([[1,2],[29,3]])
B=np.array([[10,20],[20,30]])
print(A)
print(np.dot(A,B))      # Matrix Multiplication
print(np.transpose(A))  # Transpose

[[ 1  2]
 [29  3]]
[[ 50  80]
 [350 670]]
[[ 1 29]
 [ 2  3]]


In [54]:
# Find Number Between 20 and 100
a=np.array([1,20,30,4,5,6,60,450])
b=a[(a>=20) & (a<100)]
print(b)


[20 30 60]


In [ ]:
# For making a 1D array into 2D array
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(3, 2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Array Properties
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60]])

# 1️⃣ arr.ndim → Number of Dimensions
print(arr.ndim)   # Output: 2

# 2️⃣ arr.shape → Shape (Rows, Columns)
print(arr.shape)  # Output: (2, 3)

# 3️⃣ arr.size → Total Elements in Array
print(arr.size)   # Output: 6

# 4️⃣ arr.dtype → Data Type of Elements
print(arr.dtype)  # Output: int32 or int64 

2
(2, 3)
6
int64


In [76]:
## Assignment Question
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("Middle element of 3*3 matrix: ",a[1][1])
print(a*b)
print(np.mean(a))
print(np.sum(a))
print(np.eye(4))
arr=np.array([[2,3],[1,4]])
T=np.transpose(arr)
print(T)
D=np.linalg.det(arr)
print(D)
I=np.linalg.inv(arr)
print(I)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
Middle element of 3*3 matrix:  5
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
5.0
45
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2 1]
 [3 4]]
5.000000000000001
[[ 0.8 -0.6]
 [-0.2  0.4]]
